import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import QueryProvider from "@/providers/query-provider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <QueryProvider>
          <SidebarProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
            >
              <AppSidebar />
              <main className="flex-1 min-h-screen w-full overflow-auto">
                <SidebarTrigger className="m-4" />
                <div className="p-4">
                  {children}
                </div>
              </main>
            </ThemeProvider>
            <ReactQueryDevtools initialIsOpen={false} />
          </SidebarProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
